package com.company.oop.taskManagement.commands.enums;

public enum CommandType {
    CREATENEWBUGWITHOUTASSIGNEE,
    CREATENEWBUGWITHASSIGNEE,
    CREATENEWMEMBERCOMMAND,
    CREATENEWTEAMCOMMAND,
    CREATENEWSTORYWITHOUTASSIGNEECOMMAND,
    CREATENEWSTORYWITHASSIGNEECOMMAND,
    CREATENEWFEEDBACKCOMMAND;
}
